---
title: "M8: Forecast Accuracy & Model Performance"
author: "Si Min Loo, Shaochong Xue"
output: pdf_document
always_allow_html: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), tidy=FALSE) 
```

```{r package, message=FALSE}
library(readxl)
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(kableExtra)
```

# Loading Data
```{r}
load <- read_excel("tsa-spring-2026-load-forecasting-competition/load.xlsx")
rh <- read_excel("tsa-spring-2026-load-forecasting-competition/relative_humidity.xlsx")
temp <- read_excel("tsa-spring-2026-load-forecasting-competition/temperature.xlsx")

colnames(load)
colnames(temp)
colnames(rh)
```

# Aggregate to Daily
```{r}
# turning into daily data
library(dplyr)

load_daily <- load %>%
  mutate(date = as.Date(date)) %>%
  rowwise() %>%
  mutate(load = mean(c_across(h1:h24), na.rm = TRUE)) %>%
  ungroup() %>%
  select(date, load)

temp_daily <- temp %>%
  mutate(date = as.Date(date)) %>%
  rowwise() %>%
  mutate(temp_hourly = mean(c_across(starts_with("t_ws")), na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(date) %>%
  summarise(temp = mean(temp_hourly, na.rm = TRUE))

rh_daily <- rh %>%
  mutate(date = as.Date(date)) %>%
  rowwise() %>%
  mutate(rh_hourly = mean(c_across(starts_with("rh_ws")), na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(date) %>%
  summarise(rh = mean(rh_hourly, na.rm = TRUE))

data_daily <- load_daily %>%
  left_join(temp_daily, by = "date") %>%
  left_join(rh_daily, by = "date")

data_daily
```

#transform into time series object
```{r}
ts_load_daily <- msts(
  data_daily$load,
  seasonal.periods = c(7, 365.25)
)

```

# Decompose to see the STL 

```{r}
ts_load_daily %>%
  mstl() %>%
  autoplot() +
  labs(title = "STL Decomposition of Daily Electricity Load")

```

# Initial Plots
```{r}
ggplot(data_daily, aes(x = date, y = load)) +
  geom_line() +
  labs(title = "Daily Electricity Load",
       x = "Date",
       y = "Daily Average Load") +
  theme_minimal()
```

# Train and Validation split
```{r}
train <- data_daily %>%
  filter(date >= as.Date("2005-01-01") & date <= as.Date("2010-06-30"))

valid <- data_daily %>%
  filter(date >= as.Date("2010-07-01") & date <= as.Date("2010-07-31"))

nrow(train)
nrow(valid)
head(train)
head(valid)

ts_train <- msts(train$load, seasonal.periods = c(7, 365.25))
ts_valid <- valid$load
h <- length(ts_valid)
```

# Forecasts

## Mean forecast
```{r}
mean_fit <- meanf(ts_train, h = h)
mean_scores <- accuracy(mean_fit$mean, ts_valid)
mean_scores

autoplot(mean_fit) +
  labs(title = "Mean Forecast", y = "Load")
```

## Seasonal forecast
```{r}
snaive_fit <- snaive(ts_train, h = h)
snaive_scores <- accuracy(snaive_fit$mean, ts_valid)
snaive_scores

autoplot(snaive_fit) +
  labs(title = "Seasonal Naive Forecast", y = "Load")
```

## STL + ETL
```{r}
ets_fit <- stlf(ts_train, h = h, method = "ets")
ets_scores <- accuracy(ets_fit$mean, ts_valid)
ets_scores

autoplot(ets_fit) +
  labs(title = "STL + ETS Forecast", y = "Load")

```

## ARIMA + Fourier
```{r}
arima_fourier_fit <- auto.arima(
  ts_train,
  seasonal = FALSE,
  lambda = 0,
  xreg = fourier(ts_train, K = c(2, 12))
)

arima_fourier_for <- forecast(
  arima_fourier_fit,
  xreg = fourier(ts_train, K = c(2, 12), h = h),
  h = h
)

arima_scores <- accuracy(arima_fourier_for$mean, ts_valid)
arima_scores

autoplot(arima_fourier_for) +
  labs(title = "ARIMA + Fourier Forecast", y = "Load")

```

## SARIMA
```{r}
ts_train_sarima <- ts(train$load, frequency = 7)

sarima_fit <- auto.arima(
  ts_train_sarima,
  seasonal = TRUE,
  lambda = 0
)

sarima_for <- forecast(sarima_fit, h = h)

sarima_scores <- accuracy(sarima_for$mean, ts_valid)
sarima_scores

autoplot(sarima_for) +
  labs(title = "SARIMA Forecast", y = "Load")
```


## TBATS

```{r}
tbats_fit <- tbats(ts_train)
tbats_for <- forecast(tbats_fit, h = h)

tbats_scores <- accuracy(tbats_for$mean, ts_valid)
tbats_scores

autoplot(tbats_for) +
  labs(title = "TBATS Forecast", y = "Load")

```

## NN
```{r}

```

# Model Performance, Checking Accuracy
```{r}
scores <- rbind(
  Mean            = mean_scores,
  Seasonal_Naive  = snaive_scores,
  STL_ETS         = ets_scores,
  ARIMA_Fourier   = arima_scores,
  SARIMA          = sarima_scores,
  TBATS           = tbats_scores
)

scores_df <- as.data.frame(scores)
scores_df %>%
  kbl(caption = "Forecast Accuracy Comparison") %>%
  kable_styling(full_width = FALSE)

best_model_name <- rownames(scores_df)[which.min(scores_df$RMSE)]
cat("The best model by RMSE is:", best_model_name)

```

# Refit on Best Dataset 

```{r}
ts_full <- msts(data_daily$load, seasonal.periods = c(7, 365.25))
future_h <- 31

best_fit <- auto.arima(
  ts_full,
  seasonal = FALSE,
  lambda = 0,
  xreg = fourier(ts_full, K = c(2, 12))
)

best_forecast <- forecast(
  best_fit,
  xreg = fourier(ts_full, K = c(2, 12), h = future_h),
  h = future_h
)

autoplot(best_forecast) +
  labs(title = "Final Forecast from Refit Best Model", y = "Load")

```
# Forecast Results

```{r}
# load template
template <- read.csv("./tsa-spring-2026-load-forecasting-competition/submission_template.csv")
```

## Mean
```{r}
mean_full <- meanf(ts_full, h = future_h)

mean_for <- template
mean_for$load <- as.numeric(mean_full$mean)

mean_for
```
## SNAIVE
```{r}
snaive_full <- snaive(ts_full, h = future_h)

snaive_for <- template
snaive_for$load <- as.numeric(snaive_full$mean)

snaive_for
```
```{r}
write.csv(snaive_for, "initial_result.csv", row.names = FALSE)
```




